# NUMPY

In [3]:
import numpy

In [5]:
a= numpy.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [7]:
import numpy as np

print(np.__version__)

1.26.4


In [9]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [11]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a)
print(a.ndim)

[1 2 3 4 5]
1


In [13]:
a=np.array([[1,3],[5,9]])
a[1,1]

9

In [25]:
import numpy as np 
b=np.array([[[1,3,5,7,9],[2,4,6,8,10]],[[12,34,56,78,90],[11,22,33,44,55]]])
print("dimension:",b.ndim)
b[1,0,2]

dimension: 3


56

In [25]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a.ndim)
print(a[1:4])

1
[2 3 4]


In [33]:
import numpy as np

b=np.array([6,7,8,9,10])
print(b[:3])

[6 7 8]


In [47]:
import numpy as np

a = np.array([[1, 2, 3, 4],[5,6,7,8]])
a[1,1:]

array([6, 7, 8])

In [53]:
import numpy as np
b = np.array([[[45,67,89,23],[6,7,8,9]],[[19, 52, 13, 19],[34,90,45,19]]])
b[1,1:4]

array([[34, 90, 45, 19]])