In [1]:
#sum of 2 lists

l=[1,34,6,7]
l1=[23,56,8,2]
newlist=[]

for i in range(len(l)):
    n=l[i]+l1[i]
    newlist.append(n)

print(newlist)

[24, 90, 14, 9]


In [7]:


import numpy as np

k=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
k.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [5]:
import numpy as np
k=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
k.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
#copy and view

import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9,10])

x=a.copy()
x[2]=50

print(a)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2 50  4  5  6  7  8  9 10]


In [13]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
x = a.view()
x[2] = 50

print(a)
print(x)

[ 1  2 50  4  5  6  7  8  9 10]
[ 1  2 50  4  5  6  7  8  9 10]


In [23]:
import numpy as np

a = np.array([[6,7,8],[1,2,3]])
b = np.array([[1,2,3],[4,5,6]])


addition = a+b
subtraction = a-b
multiplication = a*b
division = a/b

print("Addition:",addition)
print("Subtraction:",subtraction)
print("Multiplication:",multiplication)
print("Division:",division)

Addition: [[ 7  9 11]
 [ 5  7  9]]
Subtraction: [[ 5  5  5]
 [-3 -3 -3]]
Multiplication: [[ 6 14 24]
 [ 4 10 18]]
Division: [[6.         3.5        2.66666667]
 [0.25       0.4        0.5       ]]


In [25]:
import numpy as np

a = np.array([1, 2, 3, 4])
# print(type(a))
print(a.dtype)

int32


In [29]:
newa = np.array([1.1,2.3,4.5])

newarr = newa.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 4]
int32


In [31]:
newa = np.array(["1", "2", "3"])

newarr = newa.astype("i8")

print(newarr)
print(newarr.dtype)

[1 2 3]
int64
